### ISSUE TITLE
Implement mappings from ontology terms to BioLink model concepts

### ISSUE THREAD

**Issue by balhoff** [TranslatorIIPrototypes/cam-pipeline#5]
Review available mappings from terms used in the CAM tbox to BioLink concepts; augment the mappings as required. Determine how to store BioLink mappings within the tbox for use in query answering (i.e. what relation to ontology terms: superclass?)

**Comment by gaurav** [comment]
Ontology = Ubergraph + more
Every CAM entity should have a BioLink type; if it is not bridged, then we need to add an axiom somewhere to make that connection.

**Comment by gaurav** [comment]
Based on https://github.com/TranslatorIIPrototypes/cam-pipeline/blob/master/cam-db-model.pdf, note that the only instances in the graph are in the individual CAMs -- so as long as I create a SPARQL query that focuses on them, I don't need to worry about trying to figure out which graph the instance is in. The key question is: which instances don't have a Biolink class in their type hierarchy somewhere?

**Comment by balhoff** [comment]
Supplemental mappings are included in https://github.com/TranslatorIIPrototypes/cam-pipeline/blob/master/biolink-local.ttl
